on:
  push:
    tags:
      - "v*.*.*"

name: Build Docker images

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          labels: |
            ${{ steps.meta.outputs.labels }}
          annotations: |
            ${{ steps.meta.outputs.annotations }}
          tags: |
            ${{ steps.meta.outputs.tags }}
          cache-from: |
            type=gha
          cache-to: |
            type=gha
          push: true
